### ISSUE TITLE
breaking change in patch-version

### ISSUE THREAD

**Issue by Waize** [bpmn-io/ids#6]
### Describe the Bug

Set node-engine to `>=16` in commit https://github.com/bpmn-io/ids/commit/247af144cb7181d3aa49ff8800cb9fd499b4432c. 

### Steps to Reproduce

1. build project with this dependency defined as `^1.0.0` with node-version lower than 16

### Expected Behavior

Build will be possible.

Whit your set node-version you broke all projects depending on this dependency (e.g. using bpmn-js). 
Engine-changes should at least be a minor fix and no patch fix! Please follow the guidelines from https://semver.org/.

### Environment

- node-version 12.22.8

**Comment by barmac** [comment]
I've re-released v1.0.0 as v1.0.4 to mitigate the breaking changes, and am releasing v2.0.0 with the breaking changes inside.

**Comment by barmac** [comment]
Done. Let me know if v1.0.4 works fine for you.

**Comment by nikku** [comment]
Thanks @barmac for cleaning this up! :)
